package com.smartcampus.model;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_STATUS_CHANGED,
    TICKET_COMMENT_ADDED,
    TICKET_ASSIGNED,
    GENERAL,
    TICKET,
    BOOKING_UPDATE
}