# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://mysql-138b2c5c-amashaanjalanim-9928.e.aivencloud.com:23974/smart_campus
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_GQL1pCpg74hI01i2JpT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB

#Note:** Each member will change `yourpassword` to their own MySQL password on their own laptop. Nobody commits their real password.

# JWT
jwt.secret=smartcampus-super-secret-key-2026-must-be-at-least-256-bits-long
jwt.expiration=86400000


#----------------------------------------------------------
# File upload limits

spring.servlet.multipart.max-request-size=20MB
 
# Upload directory (relative to project root, or use absolute path)
app.upload.dir=uploads/tickets
 
# Base URL for building image URLs (change for production)
app.base-url=http://localhost:8080


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lenora.ravindi@gmail.com
spring.mail.password=trtgpzynernbqwve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.url=http://localhost:5173


cloudinary.cloud-name=djtfxuaf5
cloudinary.api-key=697898428248848
cloudinary.api-secret=p740L2ek4Fl7OFWGNzPMjkR0Wkk